spring:
  application:
    name: isamco-notification-service
  profiles:
    active: dev

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"


---

server:
  port: 9034
  servlet:
    context-path: /notifications

spring:
  config:
    activate:
      on-profile: dev
logging:
  level:
    root: INFO
    co:
      logike: DEBUG
    com:
      zaxxer:
        hikari:
          HikariConfig: DEBUG
    org:
      springframework:
        web: INFO
        http: INFO
        beans: INFO
      hibernate: INFO

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  packages-to-scan: co.logike.isamco.notifications.application.controller
configuration:
  properties:
    time-zone: GMT-5
    date-format: yyyy-MM-dd'T'HH:mm:ss*SSSZZZZ
